/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordenarnumeros;

import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author Josiene
 */
public class OrdenarNumeros extends javax.swing.JFrame {

    List<Integer> array_ordemCrescente = new ArrayList<Integer>();
    List<Integer> array_ordemDecrescente = new ArrayList<Integer>();
    
    public OrdenarNumeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_numero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        list_ordemCrescente = new java.awt.List();
        list_ordemDecrescente = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite um número :");

        jTextField_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numeroActionPerformed(evt);
            }
        });

        jLabel2.setText("Ordem Crescente: ");

        jLabel3.setText("Ordem Decrescente :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(list_ordemCrescente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(list_ordemDecrescente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list_ordemDecrescente, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(list_ordemCrescente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ordemDescrecente(){
        
         for(int linha = 0; linha < array_ordemDecrescente.size();linha++){
            for(int coluna = 0; coluna < array_ordemDecrescente.size() - 1;coluna++){
                if(array_ordemDecrescente.get(coluna) < array_ordemDecrescente.get(coluna+1)){
                    int guardaValor = array_ordemDecrescente.get(coluna);
                    array_ordemDecrescente.set(coluna,array_ordemDecrescente.get(coluna+1));
                    array_ordemDecrescente.set(coluna+1, guardaValor);
                }
            }
        }
        
        list_ordemDecrescente.removeAll();
        
        for(int i = 0;i < array_ordemDecrescente.size();i++){
            list_ordemDecrescente.add(String.valueOf(array_ordemDecrescente.get(i)));
        }
    }
    
    public void ordemCrescente(){
        
        for(int linha = 0; linha < array_ordemCrescente.size();linha++){
            for(int coluna = 0; coluna < array_ordemCrescente.size() - 1;coluna++){
                if(array_ordemCrescente.get(coluna) > array_ordemCrescente.get(coluna+1)){
                    int guardaValor = array_ordemCrescente.get(coluna);
                    array_ordemCrescente.set(coluna,array_ordemCrescente.get(coluna+1));
                    array_ordemCrescente.set(coluna+1, guardaValor);
                }
            }
        }
        
        list_ordemCrescente.removeAll();
        
        for(int i = 0;i < array_ordemCrescente.size();i++){
            list_ordemCrescente.add(String.valueOf(array_ordemCrescente.get(i)));
        }
        
    }
    
    private void jTextField_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numeroActionPerformed

        int numero = Integer.parseInt(jTextField_numero.getText());
        
        array_ordemCrescente.add(numero);
        
        array_ordemDecrescente.add(numero);
        
        if(array_ordemCrescente.size() > 1 && array_ordemDecrescente.size() > 1){
            ordemCrescente();
            ordemDescrecente();
        }else{
            list_ordemCrescente.add(String.valueOf(array_ordemCrescente.get(0)));
            list_ordemDecrescente.add(String.valueOf(array_ordemDecrescente.get(0)));
        }
        
        limparEntrada();

    }//GEN-LAST:event_jTextField_numeroActionPerformed

    public void limparEntrada(){
        jTextField_numero.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenarNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenarNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenarNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenarNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenarNumeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField_numero;
    private java.awt.List list_ordemCrescente;
    private java.awt.List list_ordemDecrescente;
    // End of variables declaration//GEN-END:variables
}
